# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "goreleaser-playground"
  homepage "https://github.com/nwtgck/goreleaser-playground"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.2/goreleaser-playground-0.1.2-darwin-amd64.tar.gz"
      sha256 "6c5df0c56c808aa08ae1514519504240942ddb4df9a6039a76eb6057e6ced9d2"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.2/goreleaser-playground-0.1.2-linux-amd64.tar.gz"
      sha256 "aa5f5f499b6051b88da8e15e3a6ef308ebf667ce6b7294df7943f8d3bfc59b90"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.2/goreleaser-playground-0.1.2-linux-armv6.tar.gz"
      sha256 "bc34022e7973159630a3ee7eaac778cf4612dcff41d76a8551c3da659413f422"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.2/goreleaser-playground-0.1.2-linux-arm64.tar.gz"
      sha256 "d0a777417d8e5331776575805fd065fa2ce60167aba57a211cd925f0309476f2"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end
end
