# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "goreleaser-playground"
  homepage "https://github.com/nwtgck/goreleaser-playground"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.3/goreleaser-playground-0.1.3-darwin-amd64.tar.gz"
      sha256 "b165d13e732ee1a760fadf7a8c08fcb5681ecece0ca968b985b52943f4c21f2d"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.3/goreleaser-playground-0.1.3-darwin-arm64.tar.gz"
      sha256 "5806f47c39ad9fd312091ce5d176f7fdcea5ad63dbd8887916a1773a127aa610"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.3/goreleaser-playground-0.1.3-linux-armv6.tar.gz"
      sha256 "f87c3026fed0afb52600a2a63a5983ca9d18af95d7f70ceef671d83154d98c72"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.3/goreleaser-playground-0.1.3-linux-arm64.tar.gz"
      sha256 "c81a3094f186a5c78ff65ded9a610f9c710530feb73ee67868531411b7991577"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/goreleaser-playground/releases/download/v0.1.3/goreleaser-playground-0.1.3-linux-amd64.tar.gz"
      sha256 "c2d5045e9b890532870597113fc0b8c2ab4d0735e2e3be834c36f3fefaef6aaa"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end
end
